INSERT INTO CM_OS_MC (MC_ID, PORT_NM, MC_NM, BAUD_RATE, DATA_BITS, PARITY_BITS, STOP_BITS, PORT_OPEN_WAIT_TIME, READ_BUFF_SIZE, READ_WAIT_TIME, READ_RETRY_CNT, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 'COM3', '기본연결', 9600, 7, 
1, 1,200,1024, 100, 
3, 'N', '2010-11-11', 'SYSTEM', '2010-11-11', 
'SYSTEM',null
);
INSERT INTO CM_OS_MC (MC_ID, PORT_NM, MC_NM, BAUD_RATE, DATA_BITS, PARITY_BITS, STOP_BITS, PORT_OPEN_WAIT_TIME, READ_BUFF_SIZE, READ_WAIT_TIME, READ_RETRY_CNT, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'USR1', 'COM1', '연결2', 9600, 7, 
1, 1,200,1024, 100, 
3, 'N', '2010-11-11', 'SYSTEM', '2010-11-11', 
'SYSTEM',null
);
---------------------

INSERT INTO CM_MSG (MSG_ID, STT_CHAR, END_CHAR, MSG_TOT_LEN, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT','ST', '0x0D0x0A', 21, 'N', 
'2010-11-11', 'SYSTEM', '2010-11-11','SYSTEM', null
);
INSERT INTO CM_MSG (MSG_ID, STT_CHAR, END_CHAR, MSG_TOT_LEN, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'USR1', '0x0D0x0A' , null , 21, 'N', 
'2010-11-11', 'SYSTEM', '2010-11-11','SYSTEM', null
);
-------------------------------------
INSERT INTO CM_MSG_ATTR (MSG_ID, ATTR_SEQ, ATTR_PRIOR, ATTR_NM, ATTR_LEN, ATTR_TYPE_CD, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 1, 1, 'sp01', 1, 
'S', 'N', '2010-11-11', 'SYSTEM', '2010-11-11',
'SYSTEM', null
);
INSERT INTO CM_MSG_ATTR (MSG_ID, ATTR_SEQ, ATTR_PRIOR, ATTR_NM, ATTR_LEN, ATTR_TYPE_CD, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 2, 2, 'header', 2, 
'S', 'N', '2010-11-11', 'SYSTEM', '2010-11-11',
'SYSTEM', null
);
INSERT INTO CM_MSG_ATTR (MSG_ID, ATTR_SEQ, ATTR_PRIOR, ATTR_NM, ATTR_LEN, ATTR_TYPE_CD, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 3, 3, 'sp02', 4, 
'S', 'N', '2010-11-11', 'SYSTEM', '2010-11-11',
'SYSTEM', null
);
INSERT INTO CM_MSG_ATTR (MSG_ID, ATTR_SEQ, ATTR_PRIOR, ATTR_NM, ATTR_LEN, ATTR_TYPE_CD, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 4, 4, 'wgt', 8, 
'N', 'N', '2010-11-11', 'SYSTEM', '2010-11-11',
'SYSTEM', null
);
INSERT INTO CM_MSG_ATTR (MSG_ID, ATTR_SEQ, ATTR_PRIOR, ATTR_NM, ATTR_LEN, ATTR_TYPE_CD, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 5, 5, 'sp03', 1, 
'S', 'N', '2010-11-11', 'SYSTEM', '2010-11-11',
'SYSTEM', null
);
INSERT INTO CM_MSG_ATTR (MSG_ID, ATTR_SEQ, ATTR_PRIOR, ATTR_NM, ATTR_LEN, ATTR_TYPE_CD, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 6, 6, 'sp03', 1, 
'S', 'N', '2010-11-11', 'SYSTEM', '2010-11-11',
'SYSTEM', null
);
INSERT INTO CM_MSG_ATTR (MSG_ID, ATTR_SEQ, ATTR_PRIOR, ATTR_NM, ATTR_LEN, ATTR_TYPE_CD, DEL_YN, RGN_DT, RGN_ID, EDT_DT, EDT_ID, SVR_TRN_DT)
 VALUES (
'DEFAULT', 7, 7, 'unit', 2, 
'S', 'N', '2010-11-11', 'SYSTEM', '2010-11-11',
'SYSTEM', null
);
